### PR TITLE
ci: add markdown linter

### PR DESCRIPTION
**Pull request by nathan-weinberg**
can run locally with `make md-lint`

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
lot of Markdown Lint errors here - I'll go through them over time but too many to do in one fell swoop myself immediately

**Comment by ckadner** [comment]
> lot of Markdown Lint errors here - I'll go through them over time but too many to do in one fell swoop myself immediately

Looks like a lot of trailing white spaces. Should be possible to use basic tools, editors and even plain git to do those fixes. I'm willing to help, but don't want to duplicate any work you already did?

**Comment by nathan-weinberg** [comment]
Haven't start anything @ckadner so if you want to push commits onto this PR be my guest! Appreciate it!

**Comment by bjhargrave** [comment]
@nathan-weinberg I updated the workflow and fixed all the linting errors.

**Review by bjhargrave — APPROVED** [review]

**Pull request merged**
