### PR TITLE
Instructions to get ollama and merlinite working

### PR DESCRIPTION
**Pull request by jjasghar**
A howto get ollama to host merlinite from huggingface

### CODE REVIEW

**Comment by lhawthorn** [comment]
@kelbrown20 Here is yet more documentation and I do not want to add unnecessarily to the sprawl, though @jjasghar's how to guide is valuable for new users. Do you have feedback on where we might either a) add this detail to existing docs or b) where we should link to this so as to make sure folks have the benefit of this knowledge.

**Comment by sroecker** [comment]
> A howto get ollama to host merlinite from huggingface

You can also just `ollama run sroecker/merlinite`
I converted the model from HF and used the provided prompt template, which differs from the example here.

**Comment by jjasghar** [comment]
> You can also just ollama run sroecker/merlinite
Neat! Yeah I figured someone would want to build it locally so they know exactly what they are getting. There's a chance you (or someone else with another fork) may have edited the `Modelfile` and made the `SYSTEM` look like this...
```dockerfile
SYSTEM """
You are Mario from Super Mario Bros. Answer as Mario, the assistant, only.
"""
```

**Comment by sroecker** [comment]
I didn't adapt the system prompt, that's something you can easily do
otherwise.

Getting the chat template right is important though:
https://ollama.com/sroecker/merlinite:latest/blobs/840577c5e55f
This should correspond to the Merlinite 7B model card:

prompt = f'<|system|>\n{sys_prompt}\n<|user|>\n{inputs}\n<|assistant|>\n'

**Comment by jjasghar** [comment]
Oh, I'm not saying you did. but these instructions are designed for you to pull directly from the upstream, and not rely on another name space, and know exactly what you're getting.

**Review by hickeyma — CHANGES_REQUESTED** [review]
Thanks @jjasghar for adding this doc. It will be useful for users.

2 things I suggest:

-  I don't think naming of file in capitals is needed. Can it go lower case?
- As per @russellb in https://github.com/instructlab/community/pull/198#issuecomment-2085232144, can we move it to `/docs/mics` directory?

**Comment by obuzek** [comment]
I wonder if it makes more sense to frame this as "running arbitrary models locally with InstructLab + ollama" instead of "running Merlinite"? With more explanation on e.g. how the Modelfile is developed?

Also I think to make it cohesive with the InstructLab project, a line at the very end explaining the `--endpoint-url` that allows you to hit the ollama model as part of your generate command would be helpful.

**Comment by jjasghar** [comment]
I had completely forgotten about this, and it's no longer accurate. Not to mention it's not Granite, which is what our defaults should be going forward. I'm going to close this.

**Pull request closed without merging**
