### PR TITLE
Complete Getting Started Guide

### PR DESCRIPTION
**Pull request by jjasghar**
A soup to nuts version of getting started.

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
These are mostly formating/editing stuff. Great work!

**Review by bjhargrave — CHANGES_REQUESTED** [review]
A round of comments.

**Review by JoeAldinger — COMMENTED** [review]
Added comments for the TOC. I fixed what @kelbrown20 mentioned in my [PR](https://github.com/instruct-lab/community/pull/153/files) so I _think_ you could pull that commit into your PR if you wanted those changes.

**Review by hickeyma — DISMISSED** [review]
Thanks @jjasghar  for pushing this quickstart. Some comments provided.

**Review by bjhargrave — CHANGES_REQUESTED** [review]
We need to use https URLs here since the audience will be using this once the repos are public.

**Review by joesepi — APPROVED** [review]
LGTM and that G stands for GREAAAAT!

**Review by bjhargrave — APPROVED** [review]

**Pull request merged**
