### PR TITLE
Update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by mmcelaney**

### CODE REVIEW

**Comment by russellb** [comment]
Well, not including the change, but if the results as of #201 are not as expected, it's a github teams configuration question

**Comment by nathan-weinberg** [comment]
Right, but the flow needs to go:

1. Update GitHub Teams
2. Update the file with the automation locally
3. Push up the change

@russellb Maybe we should make that more explicitdely stated [here](https://github.com/instructlab/community/blob/main/MAINTAINERS.md?plain=1#L3) as part of your PR

**Comment by russellb** [comment]
@nathan-weinberg take a look at #201, I added some more text to the readme

**Comment by mmcelaney** [comment]
Oh ok, updated GitHub teams appropriately and assuming this will get fixed with the next sync from the github API. Thank you!

**Pull request closed without merging**
